---

- name: hosts | exchange hostnames in hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      {% if corosync_use_internal_ip|bool %}

      {{ hostvars[item]['internal_ip'] }} {{ hostvars[item]['ansible_hostname'] }}

      {% else %}

      {{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}

      {% endif %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ hostvars[item]['ansible_hostname'] }}"
  loop: "{{ play_hosts }}"
